Part II: Query multiple tables
haroldmud/vet-clinic-data-base pull request #4
Opened 2022-07-08 22:52 UTC by haroldmud

## In this branch I did the following: :point_down: 

- Created a table named owners with the given columns.
- Created a table named owners with the given columns.
- Modified animals table.
- Inserted the given data into the `owner` table.
![InsertOwner](https://user-images.githubusercontent.com/91553966/178076971-197ebcd4-c635-4e58-9022-1e7e4c3e01a2.png)
- Inserted the given data into the species table
![$InsertSpecies](https://user-images.githubusercontent.com/91553966/178077034-afba5900-49c7-47cd-bcd5-9d473913a4d5.png)
- Modified my inserted animals so it includes the species_id value and owner_id ones.
![$AddOwners](https://user-images.githubusercontent.com/91553966/178077926-3690c09c-27ab-4e70-ba46-469bd3f25cdf.png)
- Wrote queries (using JOIN) to answer the following questions.
  - What animals belong to Melody Pond?
![$MelodyJoin](https://user-images.githubusercontent.com/91553966/178077316-6875103e-3d4c-4b43-b83c-bd69e3ef74f2.png)
  - List of all animals that are pokemon (their type is Pokemon).
![Screenshot from 2022-07-09 00-46-40](https://user-images.githubusercontent.com/91553966/178079295-a7328aee-92c1-4c5d-9bcd-abb1be3d3946.png)
  - List all owners and their animals, remember to include those that don't own any animal.
![$ownersJoinAnimals](https://user-images.githubusercontent.com/91553966/178078270-012d5479-3a5f-4f14-9bce-6d97dd2df15e.png)
  - How many animals are there per species?
![Screenshot from 2022-07-09 00-35-59](https://user-images.githubusercontent.com/91553966/178078550-a5f473d2-6c0b-4aa3-80fe-f721787a5292.png)
  - List all Digimon owned by Jennifer Orwell.
![$DigimonJoinJennifer](https://user-images.githubusercontent.com/91553966/178078723-8944f97f-e7c2-4a53-9c3f-5a2d29183862.png)
  - List all animals owned by Dean Winchester that haven't tried to escape.
 ![$DeanJoinNoEscape](https://user-images.githubusercontent.com/91553966/178079495-98e2d3f3-777e-4f1b-a414-402930e99296.png)
  - Who owns the most animals?
 ![$JoinMostAnimalOwner](https://user-images.githubusercontent.com/91553966/178078838-6f49c0d9-b3ca-4747-9d19-b81a5c0ed4a6.png)

2022-07-08 23:18 UTC, gtekle requested changes
Hi @haroldmud :wave: , 

# STATUS: Changes Requested :red_circle: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there-01](https://user-images.githubusercontent.com/44057863/178081158-c17d30e4-86ad-4370-b0a5-927c374726b4.gif)


## Highlights
:heavy_check_mark: Descriptive PR summary
:heavy_check_mark: Good use of Gitflow
:heavy_check_mark: Professional ReadMe

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly check the inline comments below and I highly suggest that you go through the materials that discuss on how to create different types JOINs (INNER, LEFT, OUTER) and what their difference is.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 23:18 UTC, gtekle commented on schema.sql
> +ALTER TABLE animals ADD COLUMN owner_id varchar(100);
- [ ] The `species_id` and `owner_id` are foreign keys for the `species` table and `owenrs` table respectively. Therefore, you should use a syntax like the following. You may also check [this](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-foreign-key/) page for further reading.
```
ALTER TABLE child_table 
ADD CONSTRAINT constraint_name 
FOREIGN KEY (fk_columns) 
REFERENCES parent_table (parent_key_columns);
```

2022-07-08 23:18 UTC, gtekle commented on data.sql
> +SELECT owner.full_name, animals.name FROM animals INNER JOIN owner ON owner.full_name = animals.owner_id WHERE owner.full_name='Melody Pond';
- [ ] You should use parallel columns when you are using JOINS. That is, we can't compare an ID with a NAME. It should be compared ID vs ID. Therefore, the correct SELECT statement with INNER JOIN would be: (**owner.id**)
`SELECT owner.full_name, animals.name FROM animals INNER JOIN owner ON owner.id = animals.owner_id WHERE owner.full_name='Melody Pond';
`

2022-07-08 23:18 UTC, gtekle commented on data.sql
> +SELECT species.name, animals.name FROM animals INNER JOIN species ON species.name = animals.species_id WHERE species.name='Pokemon';
- [ ] You should use **species.id = animals.species_id** instead for the same reason mentioned in the previous comment.

2022-07-08 23:18 UTC, gtekle commented on data.sql
> +SELECT COUNT(*) FROM animals WHERE species_id = 'Pokemon';
- [ ] If it is done correctly, `species_id` has a data type of `INT` though it is assigned a `String` value of `Pokeman`. What you need to do achieve this selection is to make a left join between the `animals`  and species table based on the **animals.species_id = species.id** and then check if **species.name = 'Pokemon'**.

2022-07-08 23:55 UTC, haroldmud commented
Thank you for the review

2022-07-09 11:34 UTC, haroldmud commented
Tried to use parallel COLUMN while using INNER JOIN for both owner_id and species_id, Implemented the Foreign key for the child tables...

2022-07-11 12:53 UTC, closed without merging